{{- /* Set up storage for the DAQ receivers.

For example, if we wanted a single, common storage location
for all daq receivers to use:

storage:
  common-daq-storage:
    storage_class: daq-storage-class
    size: 100Mb

The "storage_class" must be the name of a storageClass supported by the cluster.
In this example,
the cluster has defined a daq-specific storageClass named "daq_storage_class",
so we are configuring to use it;
but the "storage_class" could equally well be something generic like "nfss1".

The only required key is "size".

Specifying the "storage_class" is optional but highly recommended.
If omitted, the cluster default is used.
Other optional keys are "labels" and "annotations". 
*/}}
{{- range $name, $spec := .Values.storage}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{$name}}
{{- with $spec.labels}}
  labels:
{{toYaml . | indent 4}}
{{- end}}
{{- with .annotations}}
  annotations:
{{toYaml . | indent 4}}
{{- end}}
spec:
{{- with $spec.storage_class}}
  storageClassName: {{.}}
{{- end}}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{$spec.size}}
{{- end}}
