{{- /*
Launch a DAQ tango device.

If there is a receiver spec, then generate a ska-tango-util multidevice
spec by pushing the current context through the DAQ spec template.
Then convert that spec into k8s manifests by pushing it through
the ska-tango-util library functions.
*/}}
{{- if hasKey .Values "receivers" }}
{{- $filedeviceserver := tpl ($.Files.Get "data/daqs.yaml") $ | fromYaml }}
{{- $context := dict
  "name" "daq-tango"
  "deviceserver" $filedeviceserver
  "image" .Values.image
  "local" .
}}
{{ template "ska-tango-util.multidevice-config.tpl" $context }}
{{ template "ska-tango-util.multidevice-sacc-role.tpl" $context }}
{{ template "ska-tango-util.multidevice-job.tpl" $context }}
{{ template "ska-tango-util.multidevice-svc.tpl" $context }}
{{- end}}
