{{- /*
Deploy the subrack simulator/s.

  simulators:
    subracks:
      "s8-1-1":
        srmb_host: subrack-simulator-s8-1
        srmb_port: 8081

*/}}
{{- range $key, $spec := ((.Values.simulators).subracks)}}
{{- $host := $spec.srmb_host}}
{{- $port := $spec.srmb_port | default 8081}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{$host}}
  namespace: {{$.Release.Namespace}}
  labels:
    component: {{$host}}
spec:
  ports:
  - name: http
    port: {{$port}}
  type: ClusterIP
  selector:
    component: {{$host}}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$host}}
  namespace: {{$.Release.Namespace}}
  labels:
    component: {{$host}}
spec:
  selector:
    matchLabels:
      component: {{$host}}
  serviceName: {{$host}}
  replicas: 1
  template:
    metadata:
      labels:
        component: {{$host}}
    spec:
      containers:
      - name: {{$host}}
{{- with $.Values.image}}
        image: {{.registry}}/{{.name}}:{{.tag | default $.Chart.AppVersion}}
{{- end}}
        imagePullPolicy: IfNotPresent
        command:
          - "SubrackSimulator"
        env:
          - name: SUBRACK_SIMULATOR_PORT
            value: {{$port | quote}}
{{- end}}
