# -*- coding: utf-8 -*-
#
# This file is part of the MccsStation project
#
#
#
# Distributed under the terms of the GPL license.
# See LICENSE.txt for more info.

""" MCCS Station

MccsStation is the Tango device class for the MCCS Station prototype.
"""
__all__ = ["MccsStation", "main"]

# PyTango imports
from tango.server import attribute

# additional imports

from ska.base import SKAObsDevice
from tango import AttrWriteType


class MccsStation(SKAObsDevice):
    """
    MccsStation is the Tango device class for the MCCS Station prototype.

    **Properties:**

    - Device Property
    """

    # Device Properties
    # -----------------

    # ----------
    # Attributes
    # ----------

    subarrayId = attribute(
        dtype="DevLong",
        format="%i",
        polling_period=1000,
        max_value=16,
        min_value=0,
        doc="The ID of the Subarray to which this Station is allocated",
    )

    transientBufferFQDN = attribute(
        dtype="DevString",
        format="%s",
        polling_period=1000,
        doc="The fully-qualified device name of the 'transient buffer' TANGO "
        "device created by the Station",
    )

    isCalibrated = attribute(
        dtype="DevBoolean",
        polling_period=1000,
        max_value=1,
        min_value=0,
        max_alarm=1,
        doc="Defined whether the calibration cycle was successful "
        "(converged, good phase centres)",
    )

    isConfigured = attribute(
        dtype="DevBoolean",
        polling_period=1000,
        max_value=1,
        min_value=0,
        doc="True when the Station is configured, False when the Station "
        "is unconfigured or in the process of reconfiguring.",
    )

    calibrationJobId = attribute(
        dtype="DevLong",
        format="%i",
        polling_period=1000,
        doc="The job ID for calibration jobs submitted by this Station",
    )

    daqJobId = attribute(
        dtype="DevLong",
        format="%i",
        polling_period=1000,
        doc="The job ID for DAQ jobs submitted by this Station.",
    )

    dataDirectory = attribute(
        dtype="DevString",
        format="%s",
        polling_period=1000,
        doc="Parent directory for all files generated by the station.",
    )

    tileFQDNs = attribute(
        dtype=("DevString",),
        max_dim_x=16,
        format="%s",
        polling_period=1000,
        doc="Array of fully-qualified device names of the Tile devices that "
        "are associated with the Station",
    )

    beamFQDNs = attribute(
        dtype=("DevString",),
        max_dim_x=8,
        format="%s",
        polling_period=1000,
        doc="Array of full-qualified device names for the Station Beams "
        "associated with this Station",
    )

    delayCentre = attribute(
        dtype=("DevFloat",),
        access=AttrWriteType.READ_WRITE,
        max_dim_x=2,
        polling_period=1000,
        doc="""WGS84 position of the delay centre of the Station.
        todo: WGS84is a datum. What is the coordinate system?: Latitude and
        longitude? Or is it SUTM50 eastings and northings? Either way, do we
        need to allow for elevation too?""",
    )

    calibrationCoefficients = attribute(
        dtype=("DevFloat",),
        max_dim_x=512,
        polling_period=1000,
        doc="""Latest calibration coefficients for the station (split per channel/antenna)
        todo: How big should this array be? Gain and offset per antenna per
        channel.
        This station can have up to 16 tiles of up to 16 antennas, so that is
        2 x 16 x 16 = 512 coefficients per channel. But how many channels?""",
    )

    # ---------------
    # General methods
    # ---------------

    def init_device(self):
        """
        Initialises the attributes and properties of the MccsStation.
        """
        SKAObsDevice.init_device(self)
        self.set_change_event("subarrayId", True, True)
        self.set_archive_event("subarrayId", True, True)
        self.set_change_event("transientBufferFQDN", True, False)
        self.set_archive_event("transientBufferFQDN", True, False)
        self.set_change_event("isCalibrated", True, True)
        self.set_archive_event("isCalibrated", True, True)
        self.set_change_event("isConfigured", True, True)
        self.set_archive_event("isConfigured", True, True)
        self.set_change_event("tileFQDNs", True, True)
        self.set_archive_event("tileFQDNs", True, True)
        self.set_change_event("beamFQDNs", True, True)
        self.set_archive_event("beamFQDNs", True, True)

    def always_executed_hook(self):
        """
        Method always executed before any TANGO command is executed.
        """

    def delete_device(self):
        """
        Hook to delete resources allocated in init_device.

        This method allows for any memory or other resources allocated in the
        init_device method to be released.  This method is called by the device
        destructor and by the device Init command.
        """

    # ------------------
    # Attributes methods
    # ------------------

    def read_subarrayId(self):

        """
        Return the subarrayId attribute.
        """
        return 0

    def read_transientBufferFQDN(self):

        """
        Return the transientBufferFQDN attribute.
        """
        return ""

    def read_isCalibrated(self):

        """
        Return the isCalibrated attribute.
        """
        return False

    def read_isConfigured(self):

        """
        Return the isConfigured attribute.
        """
        return False

    def read_calibrationJobId(self):

        """
        Return the calibrationJobId attribute.
        """
        return 0

    def read_daqJobId(self):

        """
        Return the daqJobId attribute.
        """
        return 0

    def read_dataDirectory(self):

        """
        Return the dataDirectory attribute.
        """
        return ""

    def read_tileFQDNs(self):

        """
        Return the tileFQDNs attribute.
        """
        return ("",)

    def read_beamFQDNs(self):

        """
        Return the beamFQDNs attribute.
        """
        return ("",)

    def read_delayCentre(self):

        """
        Return the delayCentre attribute.
        """
        return (0.0,)

    def write_delayCentre(self, value):

        """
        Set the delayCentre attribute.
        """
        pass

    def read_calibrationCoefficients(self):

        """
        Return the calibrationCoefficients attribute.
        """
        return (0.0,)

    # --------
    # Commands
    # --------


# ----------
# Run server
# ----------


def main(args=None, **kwargs):
    """Main function of the MccsStation module."""

    return MccsStation.run_server(args=args, **kwargs)


if __name__ == "__main__":
    main()
