# .readthedocs.yaml
# Read the Docs configuration file.
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-24.04
  apt_packages:
  - plantuml
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    create_environment:
    - uv venv "${READTHEDOCS_VIRTUALENV_PATH}"
    install:
    - UV_PROJECT_ENVIRONMENT="${READTHEDOCS_VIRTUALENV_PATH}" uv sync --frozen --group docs

# Build documentation in the docs/src/ directory with Sphinx
sphinx:
  configuration: docs/src/conf.py
  fail_on_warning: true
