# static overrides for gitlab ci job
global:
  minikube: false

tango-base:
  itango:
    enabled: false

ska-low-mccs:
  cli:
    enabled: false

webjive:
  minikube: false

webjive-dashboard:
  enabled: false

webjive-auth:
  enabled: false

# demo config
ska-low-mccs:
  dsconfig:
    configuration_file: data/configuration_without_antennas.json
  deviceServers:
    antennas:
      instances: []
    apius:
      instances: []
