display: ":0"
xauthority: "~/.Xauthority"

global:
  labels:
    app: ska-low-mccs
  annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG
  minikube: true
  tango_host: databaseds-tango-base-test:10000
  sub-system:
    tango-base:
      enabled: false

tango-base:
  vnc:
    enabled: false
  tangorest:
    enabled: false
  tangotest:
    enabled: false
  ingress:
    enabled: false
  tangodb:
    use_pv: false
  itango:
    enabled: true

webjive:
    enabled: true

webjive-dashboard:   
    enabled: true

webjive-auth:   
    enabled: true

ska-low-mccs:
  dsconfig:
    configuration_file: data/demo_configuration.json
  deviceServers:
    tiles:
      command: "python3 -m ska.low.mccs.tile.demo_tile_device"
