{{- /*
Generate arguments to start the device server process.
Default can be changed via 'deviceServers.<server>.args'
*/ -}}
{{- define "mccs-util.deviceArgs" -}}
{{- if .device.args -}}
{{- toYaml .device.args -}}
{{- else -}}
{{- $prefix := (.global.Values.project.name |camelcase) -}}
{{- $serverName := printf "%s%s" $prefix (default ( .device.name | camelcase) .device.serverName) -}}
{{- $waitDevice := default "low-mccs/control/control" .global.Values.deviceServers.controller.fqdn -}}
- -c
- "retry --max=10 -- tango_admin --ping-device {{ $waitDevice }} &&
{{- printf " %s %s\"" $serverName (include "mccs-util.deviceInstance" .) }}
{{- end -}}
{{- end -}}
