 {{ if .Values.mccs.enabled }}

# load boilerplate configmap from template in tango-util library chart
# uses values.yaml override dsconfigFile: "data/configuration.json"
{{ template "tango-util.configmap.tpl" . }}

# memorise global scope as it isn't accessible inside range
{{- $global := . }}

# iterate over deviceServers in values.yaml
{{- range $deviceclass := .Values.deviceServers }}
# iterate over device server instances 
{{- range $deviceinstance := $deviceclass.instances }}
# create modified scope for individual instances
{{- $context := dict "instance" $deviceinstance "device" $deviceclass "global" $global }}
---
# giving a dummy Service entry ensures that the single pod is DNS addressable
{{ template "tango-util.service.tpl" $context }}

---
# Single Pod separate statefulset per Device Server
{{ template "tango-util.statefulset.tpl" $context }}

{{- end }} # instances
{{- end }} # end devcieservers

{{ end }}
