{{ if .Values.cli.enabled }}
---

apiVersion: v1
kind: Pod
metadata:
  name: cli-{{ template "mccs-util.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: cli-{{ template "mccs-util.name" . }}-{{ .Release.Name }}
    chart: {{ template "mccs-util.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  containers:
  - name: cli
    image: "{{ .Values.project.image.registry }}/{{ .Values.project.image.image }}:{{ .Values.project.image.tag }}"
    imagePullPolicy: {{ .Values.project.image.pullPolicy }}
    command:
      - /usr/local/bin/wait-for-it.sh
      - {{ template "mccs-util.databaseds" . }}
      - --timeout=30
      - --strict
      - --
      - sleep
      - infinity
    env:
{{ include "mccs-util.dbenv" . | indent 4 }}

  restartPolicy: Always
{{- with .Values.nodeSelector }}
  nodeSelector:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.affinity }}
  affinity:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.tolerations }}
  tolerations:
{{ toYaml . | indent 4 }}
{{- end }}

{{ end }}
