apiVersion: v2
description: A Helm chart for deploying the MCCS spshw prototype on Kubernetes
name: ska-low-mccs-spshw
version: 0.23.1
appVersion: 0.23.1
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  - name: ska-low-mccs-daq
    version: 0.9.2
    repository: https://artefact.skao.int/repository/helm-internal
    # version: 0.9.1-dev.c3df61d24
    # repository: https://gitlab.com/api/v4/projects/40346229/packages/helm/dev/
  - name: ska-tango-util
    version: ~0.4.11
    repository: https://artefact.skao.int/repository/helm-internal
