apiVersion: v2
description: A Helm chart for deploying the MCCS spshw prototype on Kubernetes
name: ska-low-mccs-spshw
version: 3.1.0
appVersion: 3.1.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  - name: ska-low-mccs-daq
    version: 2.0.0
    repository: https://artefact.skao.int/repository/helm-internal
    # version: 1.0.2-dev.c9987ce00
    # repository: https://gitlab.com/api/v4/projects/40346229/packages/helm/dev/
  - name: ska-tango-devices
    version: 0.2.3
    repository: https://artefact.skao.int/repository/helm-internal
    # version: 0.2.2-dev.c4df5a71e
    # repository: https://gitlab.com/api/v4/projects/66823602/packages/helm/dev
