# Default values for mccs (ska-low-mccs-spshw )
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: low-mccs-spshw 
telescope: SKA-low

labels:
  app: ska-low-mccs-spshw 
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  sub-system:
    ska-tango-base:
      enabled: false
    taranta:
      enabled: false
    archiver:
      enabled: false
  annotations:
    app.gitlab.com/app: taranta
    app.gitlab.com/env: taranta
  minikube: true
  tango_host: databaseds-tango-base-test:10000

livenessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3
readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 3
  successThreshold: 1
  failureThreshold: 3


dsconfig:
  image:
    registry: artefact.skao.int
    image: ska-tango-images-tango-dsconfig
    tag: 1.5.1
    pullPolicy: IfNotPresent
  itango:
    image:
      registry: artefact.skao.int
      image: ska-tango-images-tango-itango
      tag: 9.3.6
      pullPolicy: IfNotPresent

ska-tango-base:
  enabled: true
  vnc:
    enabled: true
  tangorest:
    enabled: true

resources:
  requests:
    cpu: 20m
    memory: 50Mi


# Default docker image - used by all of MCCS
low_mccs_spshw:
  enabled: true
  image:
    registry: artefact.skao.int
    image: ska-low-mccs-spshw
    tag: 0.2.1  # VERSION: Used to update tags on release - DO NOT REMOVE COMMENT
    pullPolicy: IfNotPresent

facility: gmrt

simulators:
  subracks:
    1:
      host: subrack-simulator-1
# This bit of code is needed to check the deployment locally.
deviceServers:
  stations:
    instances:
      1:
        enabled: false  # suppress this Tango device
  subracks:
    logging_level_default: 5
  tpms:
    logging_level_default: 5
    simulation_config: 1
    test_config: 1

nodeSelector: {}

affinity: {}
