platform:
  metadata:
    version: 0.0.9
    description: A platform configuration specification for Arcetri

  # cluster:  specified by minikube.yaml

  array:
    name: arcetri
    station_clusters:
      "a1":
        stations:
          "1":
            id: 1
            name: arcetri
            sps:
              network_address: 10.0.0.128
              subracks:
                "1":
                  srmb_host: 10.0.10.64
                  srmb_port: 8081
              tpms:
                "1":
                  host: 10.0.10.71
                  port: 10000
                  version: tpm_v1_6
                  subrack: 1
                  subrack_slot: 1
                "2":
                  host: 10.0.10.74
                  port: 10000
                  version: tpm_v1_6
                  subrack: 1
                  subrack_slot: 4
