platform:
  metadata:
    version: 0.0.9
    description: A platform configuration specification for GMRT

  # cluster:  specified by minikube.yaml

  array:
    name: gmrt
    station_clusters:
      "g1":
        cabinets:
          "1":
            # The cabinet subnet ought properly to be the second /25 in a /24
            # (the first /25 is for non-science data,
            # the second for science data).
            # This schema is currently not followed in GMRT,
            # but fortunately all we need here is any vacant /25.
            subnet: 10.0.0.0
        stations:
          "1":
            id: 1
            name: gmrt
            sps:
              cabinet: "1"
              subracks:
                "1":
                  srmb_host: 10.0.10.112
                  srmb_port: 8081
              tpms:
                "10":
                  host: 10.0.10.205
                  port: 10000
                  version: tpm_v1_6
                  subrack: 1
                  subrack_slot: 2
                "13":
                  host: 10.0.10.217
                  port: 10000
                  version: tpm_v1_6
                  subrack: 1
                  subrack_slot: 5
