platform:
  cluster:
    minikube: true
    domain: cluster.local
    services:
      jupyterhub: false  # Not a platform service
      taranta-platform: false  # Not a platform service

jupyterhub:
  enabled: true # So we'll deploy it ourselves

taranta-platform:
  enabled: true # So we'll deploy it ourselves

# TODO: https://github.com/roboll/helmfile/issues/1242#issuecomment-655423707
# We have to add these services at the root here,
# because helmfile currently only supports release conditions of the form "foo.enabled".
