platform:
  metadata:
    version: 0.0.9
    description: A platform configuration specification for Oxford

  # cluster:  specified by minikube.yaml

  array:
    name: oxford
    station_clusters:
      "o1":
        cabinets:
          "1":
            # The cabinet subnet ought properly to be the second /25 in a /24
            # (the first /25 is for non-science data,
            # the second for science data).
            # This schema is not followed in Oxford,
            # but fortunately all we need here is any vacant /25.
            subnet: 10.0.0.0
        stations:
          "1":
            id: 1
            name: oxford
            sps:
              cabinet: "1"
              daq:
                ip: 172.17.6.145
              tpms:
                "1":
                  host: 10.0.10.3
                  port: 10000
                  version: tpm_v1_2
                  subrack: 1
                  subrack_slot: 1
                "2":
                  host: 10.0.10.4
                  port: 10000
                  version: tpm_v1_2
                  subrack: 1
                  subrack_slot: 2
                "3":
                  host: 10.0.10.5
                  port: 10000
                  version: tpm_v1_2
                  subrack: 1
                  subrack_slot: 3
                "4":
                  host: 10.0.10.6
                  port: 10000
                  version: tpm_v1_2
                  subrack: 1
                  subrack_slot: 4
