{{ $localchart := . }}
{{- range $key, $deviceserver := .Values.deviceServers }}
{{- $deviceserverspec := $deviceserver }}
{{- if hasKey $deviceserver "file"}}
{{- $deviceserverspec = tpl ($.Files.Get $deviceserver.file) $ | fromYaml }}
{{- if hasKey $deviceserver "instances" }}
{{- $_ := set $deviceserverspec "instances" $deviceserver.instances }}
{{- end }}
{{- end}}  # file
{{- if hasKey $localchart.Values.global "instances" }}
{{- $_ := set $deviceserverspec "instances" $localchart.Values.global.instances }}
{{- end }}
{{- if $deviceserverspec.instances }}
{{- $context := dict "name" $key "deviceserver" $deviceserverspec "image" $deviceserver.image "local" $localchart }}
{{ template "ska-tango-util.multidevice-config.tpl" $context }}
{{ template "ska-tango-util.multidevice-sacc-role.tpl" $context }}
{{ template "ska-tango-util.multidevice-job.tpl" $context }}
{{- if or $deviceserver.deploy_service (not (hasKey $deviceserver "deploy_service")) }}
{{ template "ska-tango-util.multidevice-svc.tpl" $context }}
{{- end }}
{{- end }}  # if deviceserverspec.instances
{{- end }}  # range deviceservers
