"""This script fixes some formatting issues with the autogenerated code from ska-tango-difdoc"""

import argparse
import re
import sys
from pathlib import Path

FIELD_OR_COMMENT_RE = re.compile(r"^(?P<indent>\t*)(?::\S[^:]*:|\.\. \S)")
BULLET_RE = re.compile(r"^(?P<indent>\t*)[*+-] \S")


def _marker_match(line: str) -> "re.Match[str] | None":
    """
    Match a field/comment marker or a bullet list marker at line start.

    :param line: a single line of text.

    :return: the match object, or ``None`` if the line starts with neither.
    """
    return FIELD_OR_COMMENT_RE.match(line) or BULLET_RE.match(line)


def _leading_tabs(line: str) -> str:
    """
    Return a line's leading tab characters.

    :param line: a single line of text.

    :return: the leading run of tab characters, if any.
    """
    return line[: len(line) - len(line.lstrip("\t"))]


def _ensure_blank_before_markers(text: str) -> str:
    """
    Insert a blank line before a field/markup marker glued to prior text.

    tangodocgen flattens nested field lists (e.g. a ``:Required
    entries:`` field list nested inside a ``:param kwargs:`` body) onto
    one indentation level, merging the outer field's own text straight
    into the first line of its nested body (e.g. ``kwargs (None):
    :Required entries:``). Docutils only recognizes a field list if its
    first marker starts a line right after a blank line (or the start
    of the block), so a marker glued to a preceding non-marker line
    instead gets swallowed into that line's paragraph -- and paragraphs
    can't tolerate a later, deeper-indented line, unlike field lists.

    :param text: full contents of a generated RST file.

    :return: the text with a blank line inserted before any marker
        that directly follows non-marker text at the same indentation.
    """
    lines = text.split("\n")
    fixed = []
    for i, line in enumerate(lines):
        match = FIELD_OR_COMMENT_RE.match(line)
        previous = lines[i - 1] if i > 0 else None
        if (
            match
            # Top-level (unindented) markers are section boilerplate, e.g.
            # a ".. index::" directly under a title underline -- never
            # part of a docstring body, so never subject to this bug.
            and match.group("indent")
            and previous is not None
            and previous.strip() != ""
            and not FIELD_OR_COMMENT_RE.match(previous)
            and _leading_tabs(previous) == match.group("indent")
        ):
            fixed.append("")
        fixed.append(line)
    return "\n".join(fixed)


def _reindent_flattened_continuations(text: str) -> str:
    """
    Re-indent continuation lines that lost their hanging indent.

    :param text: full contents of a generated RST file.

    :return: the text with continuation lines indented one level
        deeper than the field/markup marker they belong to.
    """
    lines = text.split("\n")
    fixed = []
    i = 0
    while i < len(lines):
        line = lines[i]
        fixed.append(line)
        match = _marker_match(line)
        if not match:
            i += 1
            continue
        indent = match.group("indent")
        i += 1
        bumped = False
        while i < len(lines):
            candidate = lines[i]
            if candidate.strip() == "":
                break
            candidate_indent = _leading_tabs(candidate)
            if candidate_indent != indent or _marker_match(candidate):
                break
            fixed.append(f"{indent}\t{candidate[len(candidate_indent):]}")
            bumped = True
            i += 1
        # A bumped continuation is now indented deeper than its marker, so
        # docutils treats it as a nested block. If the next line dedents
        # straight back to a sibling field/marker with no blank line, that
        # nested block "ends" without one -- so make sure it always does.
        if bumped and i < len(lines) and lines[i].strip() != "":
            fixed.append("")
    return "\n".join(fixed)


def main(argv: "list[str] | None" = None) -> int:
    """
    Fix tangodocgen's generated RST files in the given directory.

    :param argv: command line arguments, for testing.

    :return: exit code.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "directory",
        nargs="?",
        default="docs/src/device-interfaces",
        type=Path,
        help="directory of tangodocgen-generated .rst files to fix",
    )
    args = parser.parse_args(argv)

    if not args.directory.is_dir():
        print(f"{args.directory} is not a directory", file=sys.stderr)
        return 1

    rst_files = sorted(args.directory.glob("*-device.rst"))
    changed = []
    for rst_file in rst_files:
        original = rst_file.read_text(encoding="utf-8")
        fixed = _reindent_flattened_continuations(_ensure_blank_before_markers(original))
        if fixed != original:
            rst_file.write_text(fixed, encoding="utf-8")
            changed.append(rst_file)

    for rst_file in changed:
        print(f"Fixed formatting in {rst_file}")
    print(f"Checked {len(rst_files)} files, fixed {len(changed)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
