apiVersion: v2
description: A Helm chart for deploying the MCCS artifact on Kubernetes
name: mccs-mvp
version: 0.0.2
type: application
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png