
global:
  labels:
    app: mccs
  annotations:
    app.gitlab.com/app: CI_PROJECT_PATH_SLUG
    app.gitlab.com/env: CI_ENVIRONMENT_SLUG
  tango_host: databaseds-tango-base-test:10000
  dsconfig:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent
  itango:
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-itango
      tag: 9.3.1
      pullPolicy: IfNotPresent

tango-base:
  vnc:
    enabled: false
  tangorest:
    enabled: false
  tangotest:
    enabled: false
  ingress:
    enabled: false
  tangodb:
    use_pv: false

mccs:
  project:
    enabled: true
    name: mccs
    image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: ska-low-mccs
      tag: latest
      pullPolicy: IfNotPresent
  cli:
    enabled: true

webjive:
  enabled: false

display: ":0"
xauthority: "~/.Xauthority"
minikube: true
