# SPSHW values for AAVS3 while temporarily located in the ITF.
global:
  minikube: false
  cluster_domain: au-aavs3.skao.int

facility:
  subracks:
    instances:
      1:
        host: 10.0.10.32
        port: 8081
  tpms:
    instances:
      1:
        host: 10.0.10.162
        port: 10000
        version: tpm_v1_6
        subrack: "1"
        subrack_bay: 3
      2:
        host: 10.0.10.164
        port: 10000
        version: tpm_v1_6
        subrack: "1"
        subrack_bay: 7

deviceServers:
  subracks:
    logging_level_default: 5
  tpms:
    logging_level_default: 5
