simulators:
  subracks:
    1:
      host: subrack-simulator-1

deviceServers:  # e.g....
  tpms:
    instances:
      1:
        host: 10.0.10.201
        port: 10000
        version: tpm_v1_6
        subrack: "1"
        subrack_bay: 1
    logging_level_default: 5
    simulation_config: 1
    test_config: 1
    resources:
      requests:
        memory: 512Mi
  stationcalibrators:
    instances:
      1:
        field_station: 1
        calibration_store: 1
  calibrationstores:
    instances:
      1:
        logging_level: 5
  mockfieldstations:
    instances:
      1:
        logging_level: 5
receivers:
  1: {}
