facility:
  tpms:
    version: tpm_v1_2
    port: 10000
    instances:
      1:
        host: 10.0.10.17
        subrack: "1"
        subrack_bay: 1
      2:
        host: 10.0.10.18
        subrack: "1"
        subrack_bay: 2
      3:
        host: 10.0.10.19
        subrack: "1"
        subrack_bay: 3
      4:
        host: 10.0.10.20
        subrack: "1"
        subrack_bay: 4
      5:
        host: 10.0.10.21
        subrack: "1"
        subrack_bay: 5
      6:
        host: 10.0.10.21
        subrack: "1"
        subrack_bay: 6
      7:
        host: 10.0.10.23
        subrack: "1"
        subrack_bay: 7
      8:
        host: 10.0.10.24
        subrack: "1"
        subrack_bay: 8
      9:
        host: 10.0.10.25
        subrack: "2"
        subrack_bay: 1
      10:
        host: 10.0.10.26
        subrack: "2"
        subrack_bay: 2
      11:
        host: 10.0.10.27
        subrack: "2"
        subrack_bay: 3
      12:
        host: 10.0.10.28
        subrack: "2"
        subrack_bay: 4
      13:
        host: 10.0.10.29
        subrack: "2"
        subrack_bay: 5
      14:
        host: 10.0.10.30
        subrack: "2"
        subrack_bay: 6
      15:
        host: 10.0.10.31
        subrack: "2"
        subrack_bay: 7
      16:
        host: 10.0.10.32
        subrack: "2"
        subrack_bay: 8

simulators:
  subracks:
    1:
      host: subrack-simulator-1
    2:
      host: subrack-simulator-2

deviceServers:
  tpms:
    logging_level_default: 5
    resources:
      requests:
        memory: 512Mi

receivers:
  1: {}
