simulators:
  subracks:
    1:
      host: subrack-simulator-1

deviceServers:  # e.g....
  tpms:
    instances:
      1:
        host: 10.0.10.201
        port: 10000
        version: tpm_v1_6
        subrack: "1"
        subrack_bay: 1
    logging_level_default: 5
    simulation_config: 1
    test_config: 1
    resources:
      requests:
        memory: 512Mi

receivers:
  1: {}
  # receivers:
  #   1:
  #     # external_ip: # optional: if provided, this is the IP address of an external DAQ receiver
  #     port:  # optional: defaults to 50051
  #     storage: daq-data  # must refer to a PVC: pre-existing or created above
  #     server_node_selector: {}  # optional
  #     server_annotations: {}  # optional
  #     server_affinity: {}  # optional
