# SPSHW values for AAVS3 while temporarily located in the ITF.
# All IP addresses are TBD.
# It's not even clear yet
# whether the AAVS3 server will be able to see
# the full AAVS3 quota of 2 subracks and 16 TPMs,
# or only the Low ITF's one subrack and two TPMs.
facility:
  subracks:
    instances:
      1:
        host: 10.135.0.1  # TODO
        port: 8081
      2:
        host: 10.135.0.2  # TODO
        port: 8081
  tpms:
    version: tpm_v1_6
    port: 10000
    instances:
      1:
        host: 10.135.1.10  # TODO
        subrack: "1"
        subrack_bay: 1
      2:
        host: 10.135.1.11  # TODO
        subrack: "1"
        subrack_bay: 2
      3:
        host: 10.135.1.12  # TODO
        subrack: "1"
        subrack_bay: 3
      4:
        host: 10.135.1.13  # TODO
        subrack: "1"
        subrack_bay: 4
      5:
        host: 10.135.1.14  # TODO
        subrack: "1"
        subrack_bay: 5
      6:
        host: 10.135.1.15  # TODO
        subrack: "1"
        subrack_bay: 6
      7:
        host: 10.135.1.16  # TODO
        subrack: "1"
        subrack_bay: 7
      8:
        host: 10.135.1.17  # TODO
        subrack: "1"
        subrack_bay: 8
      9:
        host: 10.135.2.10  # TODO
        subrack: "2"
        subrack_bay: 1
      10:
        host: 10.135.2.11  # TODO
        subrack: "2"
        subrack_bay: 2
      11:
        host: 10.135.2.12  # TODO
        subrack: "2"
        subrack_bay: 3
      12:
        host: 10.135.2.13  # TODO
        subrack: "2"
        subrack_bay: 4
      13:
        host: 10.135.2.14  # TODO
        subrack: "2"
        subrack_bay: 5
      14:
        host: 10.135.2.15  # TODO
        subrack: "2"
        subrack_bay: 6
      15:
        host: 10.135.2.16  # TODO
        subrack: "2"
        subrack_bay: 7
      16:
        host: 10.135.2.17  # TODO
        subrack: "2"
        subrack_bay: 8

simulators:
  subracks:
    1:
      host: subrack-simulator-1
    2:
      host: subrack-simulator-2

deviceServers:
  subracks:
    logging_level_default: 5
  tpms:
    logging_level_default: 5
    simulation_config: 1
    test_config: 1
