simulators:
  subracks:
    1:
      host: subrack-simulator-1

deviceServers:  # e.g....
  tpms:
    instances:
      2:
        host: 10.0.10.201
        port: 10000
        version: tpm_v1_6
        subrack: "1"
        subrack_bay: 1
    logging_level_default: 5
    simulation_config: 1
    test_config: 1
    resources:
      requests:
        memory: 512Mi
