defaults:
  logging_level_default: 5

platform:
  stations:
    oxford:
      sps:
        subracks:
          "1":
            srmb_host: subrack_simulator
            srmb_port: 8081
            pdu_trl: low-mccs/pdu/ci-1
            simulated: true

# Use helm_values to set arbitrary helm values.
# These are passed through to the helm values file as-is.
# For example,
#
helm_values:
  # Null ParentTRL given by platform spec, currently the only place to do this.
  ska-tango-devices:
    devices:
      SpsStation:
        low-mccs/spsstation/oxford:
          ParentTRL: ""
#   image:
#     registry: registry.gitlab.com/ska-telescope/mccs/ska-low-mccs-spshw
#     tag: 0.11.0-dev.cc21201e6

#   ska-low-mccs-daq:
#     image:
#       registry: registry.gitlab.com/ska-telescope/mccs/ska-low-mccs-daq
#       tag: 0.5.0-dev.cfc920d91
