defaults:
  logging_level_default: 5

subarrays:  # 2 subarrays, no defaults overridden
  "1": {}
    # enabled: false  # for example
  "2": {}
    # logging_level_default: 4  # for example

subarraybeams:  # 6 subarraybeams, no defaults overridden
  "1": {}
    # enabled: false  # for example
  "2": {}
    # logging_level_default: 4  # for example
  "3": {}
  "4": {}
  "5": {}
  "6": {}

# Use helm_values to set arbitrary helm values.
# These are passed through to the helm values file as-is.
# For example,
#
helm_values:
  # Null ParentTRL given by platform spec, currently the only place to do this.
  ska-tango-devices:
    devices:
      SpsStation:
        low-mccs/spsstation/jbo:
          ParentTRL: ""
#   image:
#     registry: registry.gitlab.com/ska-telescope/mccs/ska-low-mccs-spshw
#     tag: 0.11.0-dev.cc21201e6

#   ska-low-mccs-daq:
#     image:
#       registry: registry.gitlab.com/ska-telescope/mccs/ska-low-mccs-daq
#       tag: 0.5.0-dev.cfc920d91
