apiVersion: v2
name: umbrella-mccs-spshw 
description: A Helm chart for Kubernetes MCCS
type: application
version: 0.4.0
appVersion: 0.4.0
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
  - name: ska-low-mccs-spshw 
    version: 0.4.0
    repository: file://../ska-low-mccs-spshw 

  # Jupyterhub
  - name: jupyterhub
    version: 2.0.0
    repository: https://jupyterhub.github.io/helm-chart/

  # Taranta
  - name: ska-tango-taranta-dashboard
    version: 1.4.0
    repository: https://artefact.skao.int/repository/helm-internal
  - name: ska-tango-taranta-dashboard-pvc
    version: 1.4.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta-dashboard.enabled
  - name: ska-tango-taranta
    version: 2.2.0
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-tango-tangogql
    version: 1.3.6
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled
  - name: ska-tango-taranta-auth
    version: 0.1.6
    repository: https://artefact.skao.int/repository/helm-internal
    condition: ska-taranta.enabled

  # base
  - name: ska-tango-util
    version: 0.3.23
    repository: https://artefact.skao.int/repository/helm-internal  
  - name: ska-tango-base
    version: 0.3.10
    repository: https://artefact.skao.int/repository/helm-internal
