environments:
  default:
    kubeContext: minikube
    values:
      - platform/minikube.yaml
  stfc-ci:
    values:
      - platform/minikube.yaml
      - spshw/values/values-stfc-ci.yaml
  aa0.5:
    kubeContext: low-itf  # temporary target platform
    values:
      - platform/aa0.5/aa0-5.yaml
      - platform/aa0.5/aa0-5-s8-1.yaml
      - platform/aa0.5/aa0-5-s8-6.yaml
      - platform/aa0.5/aa0-5-s9-2.yaml
      - platform/aa0.5/aa0-5-s9-5.yaml
      - platform/aa0.5/aa0-5-s10-3.yaml
      - platform/aa0.5/aa0-5-s10-6.yaml
      - spshw/values/values-aa0-5.yaml
  aa0.5-minikube:
    kubeContext: minikube
    values:
      - platform/aa0.5/aa0-5.yaml
      - platform/aa0.5/aa0-5-s8-1.yaml
      - platform/aa0.5/aa0-5-s8-6.yaml
      - platform/aa0.5/aa0-5-s9-2.yaml
      - platform/aa0.5/aa0-5-s9-5.yaml
      - platform/aa0.5/aa0-5-s10-3.yaml
      - platform/aa0.5/aa0-5-s10-6.yaml
      - spshw/values/values-aa0-5.yaml
      - platform/minikube.yaml
  aavs3-production:
    kubeContext: aavs3-production
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/helmfile.d/values/aavs3.yaml?ref=a1dd298523a65fe8a5aac6c6664eaf90c4ea9077
      - spshw/values/values-aavs3.yaml
  aavs3-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/helmfile.d/values/aavs3.yaml?ref=a1dd298523a65fe8a5aac6c6664eaf90c4ea9077
      - spshw/values/values-aavs3.yaml
      - platform/minikube.yaml
  arcetri:
    kubeContext: minikube
    values:
      - platform/arcetri.yaml
      - spshw/values/values-arcetri.yaml
      - platform/minikube.yaml
  gmrt:
    kubeContext: minikube
    values:
      - platform/gmrt.yaml
      - spshw/values/values-gmrt.yaml
      - platform/minikube.yaml
  low-itf:
    kubeContext: low-itf
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=12e33d6b6f048de78f8d51a0a7a453b6a6131001
      - spshw/values/values-low-itf.yaml
  low-itf-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=12e33d6b6f048de78f8d51a0a7a453b6a6131001
      - spshw/values/values-low-itf.yaml
      - platform/minikube.yaml
  oxford:
    kubeContext: minikube
    values:
      - platform/oxford.yaml
      - spshw/values/values-oxford.yaml
      - platform/minikube.yaml
  psi-low:
    kubeContext: psi-low
    values:
      - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=c8c06f0337458247133e144c91d0b3567e51c3e8
      - spshw/values/values-psi-low.yaml
  psi-low-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=c8c06f0337458247133e144c91d0b3567e51c3e8
      - spshw/values/values-psi-low.yaml
      - platform/minikube.yaml
      - spshw/values/values-psi-low-minikube.yaml

---

repositories:
  - name: skao
    url: https://artefact.skao.int/repository/helm-internal
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jupyterhub
    url: https://jupyterhub.github.io/helm-chart

releases:
  - name: ska-low-mccs-spshw
    namespace: ska-low-mccs
    chart: ../charts/ska-low-mccs-spshw
    version: 0.11.0
    values:
      - values/globals.yaml.gotmpl
      - spshw/templates/spsstations.yaml.gotmpl
      - spshw/templates/calibration.yaml.gotmpl
      - spshw/templates/subracks.yaml.gotmpl
      - spshw/templates/tpms.yaml.gotmpl
      - spshw/templates/daqs.yaml.gotmpl

{{- $_tango_host_provided := dig "platform" "cluster" "services" "tango-base" "tango-host" "" .Values}}
{{- $tango_host_provided := dig "overrides" "cluster" "services" "tango-base" "tango-host" $_tango_host_provided .Values}}
{{- if not $tango_host_provided}}
  - name: ska-tango-base
    namespace: ska-low-mccs
    chart: skao/ska-tango-base
    version: 0.4.7
    values:
      - values/globals.yaml.gotmpl
{{- end}}

{{- $_skuid_provided := dig "platform" "cluster" "services" "skuid" "url" "" .Values}}
{{- $skuid_provided := dig "overrides" "cluster" "services" "skuid" "url" $_skuid_provided .Values}}
{{- if not $skuid_provided}}
  - name: ska-ser-skuid
    namespace: ska-low-mccs
    chart: skao/ska-ser-skuid
    version: 3.3.3
    values:
      - values/skuid.yaml
{{- end}}

{{- $_jupyterhub_provided := dig "platform" "cluster" "services" "jupyterhub" false .Values}}
{{- $jupyterhub_provided := dig "overrides" "cluster" "services" "jupyterhub" $_jupyterhub_provided .Values}}
{{- if not $jupyterhub_provided}}
  - name: jupyterhub
    namespace: ska-low-mccs
    chart: jupyterhub/jupyterhub
    version: 3.1.0
    values:
      - values/jupyterhub.yaml
{{- end}}

{{- $_taranta_platform_provided := dig "platform" "cluster" "services" "taranta-platform" false .Values}}
{{- $taranta_platform_provided := dig "overrides" "cluster" "services" "taranta-platform" $_taranta_platform_provided .Values}}
{{- if not $taranta_platform_provided}}
  - name: taranta-dashboard
    namespace: ska-low-mccs
    chart: skao/ska-tango-taranta-dashboard
    version: 1.4.0
    values:
      - ingress:
          enabled: true
          hostname: "*"
  - name: taranta-dashboard-pvc
    namespace: ska-low-mccs
    chart: skao/ska-tango-taranta-dashboard-pvc
    version: 1.4.1
  - name: taranta-auth
    namespace: ska-low-mccs
    chart: skao/ska-tango-taranta-auth
    version: 0.1.6
    values:
      - ingress:
          enabled: true
          hostname: "*"
{{- end}}

  - name: taranta
    namespace: ska-low-mccs
    chart: skao/ska-tango-taranta
    version: 2.4.2
    values:
      - values/taranta.yaml

  - name: tangogql
    namespace: ska-low-mccs
    chart: skao/ska-tango-tangogql
    version: 1.3.10
    values:
      - values/globals.yaml.gotmpl
      - ska-tango-base:
          enabled: false
