environments:
  default:
    values:
      - platform/minikube.yaml
  stfc-ci:
    values:
      - platform/minikube.yaml
      - spshw/values/values-stfc-ci.yaml
  aavs3:
    values:
      # - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/helmfile.d/values/aavs3.yaml
      - platform/aavs3.yaml
      - spshw/values/values-aavs3.yaml.gotmpl
  aavs3-minikube:
    values:
      # - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/helmfile.d/values/aavs3.yaml
      - platform/aavs3.yaml
      - spshw/values/values-aavs3.yaml.gotmpl
      - platform/minikube.yaml
  aavs3-in-low-itf:
    values:
      # - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/helmfile.d/values/aavs3-in-low-itf.yaml
      - platform/aavs3-in-low-itf.yaml
      - spshw/values/values-aavs3-in-low-itf.yaml.gotmpl
  aavs3-in-low-itf-minikube:
    values:
      # - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/helmfile.d/values/aavs3-in-low-itf.yaml
      - platform/aavs3-in-low-itf.yaml
      - spshw/values/values-aavs3-in-low-itf.yaml.gotmpl
      - platform/minikube.yaml
  arcetri:
    values:
      - platform/arcetri.yaml
      - spshw/values/values-arcetri.yaml.gotmpl
  gmrt:
    values:
      - platform/gmrt.yaml
      - spshw/values/values-gmrt.yaml.gotmpl
  oxford:
    values:
      - platform/oxford.yaml
      - spshw/values/values-oxford.yaml.gotmpl
  psi-low:
    values:
      # - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=c0120fa49d0e8dba79a035a225f65be15eb23dc6
      - platform/psi-low.yaml
      - spshw/values/values-psi-low.yaml.gotmpl
  psi-low-minikube:
    values:
      # - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=c0120fa49d0e8dba79a035a225f65be15eb23dc6
      - platform/psi-low.yaml
      - spshw/values/values-psi-low.yaml.gotmpl
      - platform/minikube.yaml
      - spshw/values/values-psi-low-minikube.yaml
---

repositories:
  - name: skao
    url: https://artefact.skao.int/repository/helm-internal
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: ska-low-mccs-spshw
    namespace: ska-low-mccs-spshw
    chart: ../charts/ska-low-mccs-spshw
    version: 0.7.1
    values:
      - spshw/templates/globals.yaml.gotmpl
      - spshw/templates/spsstations.yaml.gotmpl
      - spshw/templates/calibration.yaml.gotmpl
      - spshw/templates/subracks.yaml.gotmpl
      - spshw/templates/tpms.yaml.gotmpl
      - spshw/templates/daqs.yaml.gotmpl
  - name: ska-ser-skuid
    namespace: ska-low-mccs-spshw
    chart: skao/ska-ser-skuid
    version: 3.3.3
    values:
      - values/skuid.yaml
  - name: jupyterhub
    namespace: ska-low-mccs-spshw
    chart: jupyterhub/jupyterhub
    version: 2.0.0
    values:
      - values/jupyterhub.yaml
    condition: jupyterhub.enabled
  - name: taranta-dashboard
    namespace: ska-low-mccs-spshw
    chart: skao/ska-tango-taranta-dashboard
    version: 1.4.0
    condition: taranta-platform.enabled
    values:
      - ingress:
          enabled: true
          hostname: "*"
  - name: taranta-dashboard-pvc
    namespace: ska-low-mccs-spshw
    chart: skao/ska-tango-taranta-dashboard-pvc
    version: 1.4.0
    condition: taranta-platform.enabled
  - name: taranta-auth
    namespace: ska-low-mccs-spshw
    chart: skao/ska-tango-taranta-auth
    version: 0.1.6
    condition: taranta-platform.enabled
    values:
      - ingress:
          enabled: true
          hostname: "*"
  - name: taranta
    namespace: ska-low-mccs-spshw
    chart: skao/ska-tango-taranta
    version: 2.2.4
    values:
      - values/taranta.yaml
  - name: tangogql
    namespace: ska-low-mccs-spshw
    chart: skao/ska-tango-tangogql
    version: 1.3.8
    values:
      - ska-tango-base:
          enabled: false
