environments:
  default:
    values:
      - platform/minikube.yaml
  stfc-ci:
    values:
      - platform/minikube.yaml
      - spshw/values/values-stfc-ci.yaml
  aa0.5:
    values:
      - platform/aa0.5/aa0-5.yaml
      - platform/aa0.5/aa0-5-s8-1.yaml
      - platform/aa0.5/aa0-5-s8-6.yaml
      - platform/aa0.5/aa0-5-s9-2.yaml
      - platform/aa0.5/aa0-5-s9-5.yaml
      - platform/aa0.5/aa0-5-s10-3.yaml
      - platform/aa0.5/aa0-5-s10-6.yaml
      - spshw/values/values-aa0-5.yaml
  aa0.5-minikube:
    values:
      - platform/aa0.5/aa0-5.yaml
      - platform/aa0.5/aa0-5-s8-1.yaml
      - platform/aa0.5/aa0-5-s8-6.yaml
      - platform/aa0.5/aa0-5-s9-2.yaml
      - platform/aa0.5/aa0-5-s9-5.yaml
      - platform/aa0.5/aa0-5-s10-3.yaml
      - platform/aa0.5/aa0-5-s10-6.yaml
      - spshw/values/values-aa0-5.yaml
      - platform/minikube.yaml
  aavs3:
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/helmfile.d/values/aavs3.yaml?ref=16ecec50d5691291157e47ec98ffd536bf255e79
      - spshw/values/values-aavs3.yaml
  aavs3-minikube:
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/helmfile.d/values/aavs3.yaml?ref=16ecec50d5691291157e47ec98ffd536bf255e79
      - spshw/values/values-aavs3.yaml
      - platform/minikube.yaml
  aavs3-in-low-itf:
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/helmfile.d/values/aavs3-in-low-itf.yaml?ref=16ecec50d5691291157e47ec98ffd536bf255e79
      - spshw/values/values-aavs3-in-low-itf.yaml
  aavs3-in-low-itf-minikube:
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/helmfile.d/values/aavs3-in-low-itf.yaml?ref=16ecec50d5691291157e47ec98ffd536bf255e79
      - spshw/values/values-aavs3-in-low-itf.yaml
      - platform/minikube.yaml
  arcetri:
    values:
      - platform/arcetri.yaml
      - spshw/values/values-arcetri.yaml
  gmrt:
    values:
      - platform/gmrt.yaml
      - spshw/values/values-gmrt.yaml
  low-itf:
    kubeContext: low-itf
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=53c6326fb8d5bf65ee3575722e1cb2e14e79726a
      - spshw/values/values-low-itf.yaml
  low-itf-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=53c6326fb8d5bf65ee3575722e1cb2e14e79726a
      - spshw/values/values-low-itf.yaml
      - platform/minikube.yaml
  oxford:
    values:
      - platform/oxford.yaml
      - spshw/values/values-oxford.yaml
  psi-low:
    values:
      - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=20895318908c03c21def95a4b0b44caa79c58b38
      - spshw/values/values-psi-low.yaml
  psi-low-minikube:
    values:
      - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=20895318908c03c21def95a4b0b44caa79c58b38
      - spshw/values/values-psi-low.yaml
      - platform/minikube.yaml
      - spshw/values/values-psi-low-minikube.yaml
---

values:
{{- $_jupyterhub := dig "platform" "cluster" "services" "jupyterhub" false .Values}}
{{- $jupyterhub := dig "overrides" "cluster" "services" "jupyterhub" $_jupyterhub .Values}}
{{- $_taranta_platform := dig "platform" "cluster" "services" "taranta-platform" false .Values}}
{{- $taranta_platform := dig "overrides" "cluster" "services" "taranta-platform" $_taranta_platform .Values}}
  - jupyterhub:
      enabled: {{not $jupyterhub}}
  - taranta-platform:
      enabled: {{not $taranta_platform}}

---

repositories:
  - name: skao
    url: https://artefact.skao.int/repository/helm-internal
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jupyterhub
    url: https://jupyterhub.github.io/helm-chart

releases:
  - name: ska-low-mccs-spshw
    namespace: ska-low-mccs
    chart: ../charts/ska-low-mccs-spshw
    version: 0.8.0
    values:
      - spshw/templates/globals.yaml.gotmpl
      - spshw/templates/spsstations.yaml.gotmpl
      - spshw/templates/calibration.yaml.gotmpl
      - spshw/templates/subracks.yaml.gotmpl
      - spshw/templates/tpms.yaml.gotmpl
      - spshw/templates/daqs.yaml.gotmpl
  - name: ska-ser-skuid
    namespace: ska-low-mccs
    chart: skao/ska-ser-skuid
    version: 3.3.3
    values:
      - values/skuid.yaml
  - name: jupyterhub
    namespace: ska-low-mccs
    chart: jupyterhub/jupyterhub
    version: 3.0.0
    values:
      - values/jupyterhub.yaml
    condition: jupyterhub.enabled
  - name: taranta-dashboard
    namespace: ska-low-mccs
    chart: skao/ska-tango-taranta-dashboard
    version: 1.4.0
    condition: taranta-platform.enabled
    values:
      - ingress:
          enabled: true
          hostname: "*"
  - name: taranta-dashboard-pvc
    namespace: ska-low-mccs
    chart: skao/ska-tango-taranta-dashboard-pvc
    version: 1.4.0
    condition: taranta-platform.enabled
  - name: taranta-auth
    namespace: ska-low-mccs
    chart: skao/ska-tango-taranta-auth
    version: 0.1.6
    condition: taranta-platform.enabled
    values:
      - ingress:
          enabled: true
          hostname: "*"
  - name: taranta
    namespace: ska-low-mccs
    chart: skao/ska-tango-taranta
    version: 2.2.4
    values:
      - values/taranta.yaml
  - name: tangogql
    namespace: ska-low-mccs
    chart: skao/ska-tango-tangogql
    version: 1.3.8
    values:
      - ska-tango-base:
          enabled: false
