environments:
  default:
    kubeContext: minikube
    values:
      - platform/minikube.yaml
  minikube:
    values:
      - platform/minikube.yaml
      - spshw/values/values-ci.yaml
  stfc-ral:
    kubeContext: stfc-ral
    values:
      - platform/stfc-ral.yaml
  stfc-ral-software:
    kubeContext: stfc-ral
    values:
      - platform/stfc-ral.yaml
      - spshw/values/values-ral-software.yaml
  stfc-ral-firmware:
    kubeContext: stfc-ral
    values:
      - platform/stfc-ral.yaml
      - spshw/values/values-ral-firmware.yaml
  stfc-ral-partial:
    kubeContext: stfc-ral
    values:
      - platform/stfc-ral.yaml
      - spshw/values/values-ral-partial.yaml
  stfc-ci:
    values:
      - platform/stfc-ci.yaml
      - spshw/values/values-ci.yaml
  aa0.5-production:
    kubeContext: infra:au-aa-mccs-cloud01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/aa0.5.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s8-1.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s8-6.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s9-2.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s10-3.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - spshw/values/values-aa0-5.yaml
  aa0.5-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/aa0.5.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s8-1.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s8-6.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s9-2.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - git::https://gitlab.com/ska-telescope/ska-low-deployment.git@tmdata/instrument/mccs-configuration/s10-3.yaml?ref=f0f1478a2b5ebc240222db8ede01b94aa7f977a9
      - spshw/values/values-aa0-5.yaml
      - platform/minikube.yaml
  aavs3-production:
    kubeContext: infra:au-itf-aavs302-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=d2b1606c6249c193e4ac08932951da2043fbf21a
      - spshw/values/values-aavs3.yaml
  aavs3-staging:
    kubeContext: infra:au-itf-k8s-master01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=d2b1606c6249c193e4ac08932951da2043fbf21a
      - spshw/values/values-aavs3.yaml
      - spshw/values/values-aavs3-staging.yaml
  aavs3-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-low-aavs3.git@/tmdata/instrument/mccs-configuration/aavs3.yaml?ref=d2b1606c6249c193e4ac08932951da2043fbf21a
      - spshw/values/values-aavs3.yaml
      - platform/minikube.yaml
  arcetri:
    kubeContext: minikube
    values:
      - platform/arcetri.yaml
      - spshw/values/values-arcetri.yaml
      - platform/minikube.yaml
  gmrt:
    kubeContext: minikube
    values:
      - platform/gmrt.yaml
      - spshw/values/values-gmrt.yaml
      - platform/minikube.yaml
  low-itf:
    kubeContext: infra:au-itf-k8s-master01-k8s
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=d82c9910a6286a5ec258a32366f4ce2930cee5d6
      - spshw/values/values-low-itf.yaml
  low-itf-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/aiv/ska-low-itf.git@/helmfile.d/values/platform.yaml?ref=d82c9910a6286a5ec258a32366f4ce2930cee5d6
      - spshw/values/values-low-itf.yaml
      - platform/minikube.yaml
  oxford:
    kubeContext: minikube
    values:
      - platform/oxford.yaml
      - spshw/values/values-oxford.yaml
      - platform/minikube.yaml
  psi-low:
    kubeContext: psi-low
    values:
      - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=a066f45a12d373328189f390c220184cf13c1af0
      - spshw/values/values-psi-low.yaml
  psi-low-minikube:
    kubeContext: minikube
    values:
      - git::https://gitlab.com/ska-telescope/ska-psi-low.git@/helmfile.d/values/platform.yaml?ref=a066f45a12d373328189f390c220184cf13c1af0
      - spshw/values/values-psi-low.yaml
      - platform/minikube.yaml
      - spshw/values/values-psi-low-minikube.yaml

---

repositories:
  - name: skao
    url: https://artefact.skao.int/repository/helm-internal
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jupyterhub
    url: https://jupyterhub.github.io/helm-chart
  - name: ska-low-mccs-daq
    url: https://gitlab.com/api/v4/projects/40346229/packages/helm/dev/

releases:
  - name: ska-low-mccs-spshw
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: ../charts/ska-low-mccs-spshw
    version: ~0.15.0
    values:
      - .deploy/helmfile.d/templates/globals.yaml.gotmpl
      - .deploy/helmfile.d/templates/spshw/daqs.yaml.gotmpl
      - .deploy/helmfile.d/templates/spshw/spsstations.yaml.gotmpl
      - .deploy/helmfile.d/templates/spshw/subracks.yaml.gotmpl
      - .deploy/helmfile.d/templates/spshw/tpms.yaml.gotmpl
      - .deploy/helmfile.d/templates/spshw/ska-low-mccs-daq.yaml.gotmpl
      - .deploy/helmfile.d/templates/helm-values.yaml.gotmpl

{{- $_tango_host_provided := dig "platform" "cluster" "services" "tango-base" "tango-host" "" .Values}}
{{- $tango_host_provided := dig "overrides" "cluster" "services" "tango-base" "tango-host" $_tango_host_provided .Values}}
{{- if not $tango_host_provided}}
  - name: ska-tango-base
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-base
    version: ~0.4.7
    values:
      - .deploy/helmfile.d/templates/globals.yaml.gotmpl
{{- end}}

{{- $_skuid_provided := dig "platform" "cluster" "services" "skuid" "url" "" .Values}}
{{- $skuid_provided := dig "overrides" "cluster" "services" "skuid" "url" $_skuid_provided .Values}}
{{- if not $skuid_provided}}
  - name: ska-ser-skuid
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-ser-skuid
    version: ~3.3.3
    values:
      - .deploy/helmfile.d/templates/skuid.yaml
{{- end}}

{{- $_jupyterhub_provided := dig "platform" "cluster" "services" "jupyterhub" false .Values}}
{{- $jupyterhub_provided := dig "overrides" "cluster" "services" "jupyterhub" $_jupyterhub_provided .Values}}
{{- if not $jupyterhub_provided}}
  - name: jupyterhub
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: jupyterhub/jupyterhub
    version: 3.1.0
    values:
      - .deploy/helmfile.d/templates/jupyterhub.yaml
{{- end}}

{{- $_taranta_platform_provided := dig "platform" "cluster" "services" "taranta-platform" false .Values}}
{{- $taranta_platform_provided := dig "overrides" "cluster" "services" "taranta-platform" $_taranta_platform_provided .Values}}
{{- if not $taranta_platform_provided}}
  - name: taranta-dashboard
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-taranta-dashboard
    version: 1.4.1  # TODO: pinning for now because 1.4.2 is breaking
    values:
      - ingress:
          enabled: true
          hostname: "*"
  - name: taranta-dashboard-pvc
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-taranta-dashboard-pvc
    version: 1.4.1  # TODO: pinning for now because 1.4.2 is breaking
  - name: taranta-auth
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-taranta-auth
    version: ~0.1.6
    values:
      - ingress:
          enabled: true
          hostname: "*"
{{- end}}

  - name: taranta
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-taranta
    version: ~2.5.1
    values:
      - .deploy/helmfile.d/templates/taranta.yaml

  - name: tangogql
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-tangogql
    version: ~1.3.10
    values:
      - .deploy/helmfile.d/templates/globals.yaml.gotmpl
      - ska-tango-base:
          enabled: false