environments:
  minikube-ci:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?7728994278aa03849fda4d092c1fd4797a5f02e6#tmdata/minikube
        datasets:
        - platform.yaml
      - source: ../../../../local_telmodel
        datasets:
        - ci-1.yaml
        - real-daq-1.yaml
    - config_files:
      - values/values-ci.yaml
      datacentre: minikube
  stfc-ci:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?7728994278aa03849fda4d092c1fd4797a5f02e6#tmdata/stfc-cloud
        datasets:
        - platform.yaml
      - source: ../../../../local_telmodel
        datasets:
        - ci-1.yaml
        - real-daq-1.yaml
    - config_files:
      - values/values-ci.yaml
  aa0.5:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/ska-low-tmdata?689ff1ab69b56a8537650b403ef6865caa5c9e27#tmdata
        datasets:
        - aa0.5.yaml
        - stations/s8-1.yaml
        - stations/s8-6.yaml
        - stations/s9-1.yaml
        - stations/s9-2.yaml
        - stations/s10-3.yaml
        - channeliser_rounding.yaml
      config_files:
      - values/values-aa0-5.yaml
  arcetri:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?80a50483154825f785545d6acfbe8724030d14a0#tmdata/arcetri
        datasets:
        - arcetri.yaml
        - stations/arcetri.yaml
    - config_files:
      - values/values-arcetri.yaml
      datacentre: minikube
  gmrt:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?d05713b7f9e0808c8974b979737de39db647dbd8#tmdata/gmrt
        datasets:
        - gmrt.yaml
        - stations/gmrt.yaml
    - config_files:
      - values/values-gmrt.yaml
      datacentre: minikube
  low-itf:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/aiv/ska-low-itf?201bcf1edbadee4597f99931d4100d3665cd5c86#tmdata
        datasets:
        - stations/itf1.yaml
        - low-itf.yaml
        - stations/itf1.yaml
        - stations/itf2.yaml
      config_files:
        - values/values-low-itf.yaml
  low-itf-minikube:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/aiv/ska-low-itf?201bcf1edbadee4597f99931d4100d3665cd5c86#tmdata
        datasets:
        - stations/itf2.yaml
        - low-itf.yaml
        - stations/itf1.yaml
        - stations/itf2.yaml
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?80a50483154825f785545d6acfbe8724030d14a0#tmdata/minikube
        datasets:
        - platform.yaml
      config_files:
        - values/values-low-itf.yaml
  oxford:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?80a50483154825f785545d6acfbe8724030d14a0#tmdata/oxford
        datasets:
        - stations/oxford.yaml
        - oxford.yaml
    - config_files:
      - values/values-oxford.yaml
      datacentre: minikube
  psi-low:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/ska-psi-low?6f8e04db2f1fe47fb9d4ba946d3bad8e91fe3e56#tmdata
        datasets:
        - stations/stations.yaml # needs to be first see LOW-988 ska-telescope/ska-low-deployment@7c57c32a
        - psi-low.yaml
    - config_files:
      - values/values-psi-low.yaml
      datacentre: psi-low
  psi-low-minikube:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/ska-psi-low?35b5a87b5b18ba56969f034210b3458c9fe997b2#tmdata
        datasets:
        - stations/stations.yaml # needs to be first see LOW-988 ska-telescope/ska-low-deployment@7c57c32a
        - psi-low.yaml
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?80a50483154825f785545d6acfbe8724030d14a0#tmdata/minikube
        datasets:
        - platform.yaml
      config_files:
      - values/values-psi-low.yaml
      datacentre: psi-low
  ral-software:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?de912ea5e026dbf471a1ec702747aae644ac0504#tmdata/stfc-ral
        datasets:
        - stfc-ral.yaml
        - stations/stfc-ral-software.yaml
    - config_files:
      - values/values-ral-software.yaml
      datacentre: stfc-ral
  ral-software-minikube:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?de912ea5e026dbf471a1ec702747aae644ac0504#tmdata/stfc-ral
        datasets:
        - stations/stfc-ral-software.yaml
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?de912ea5e026dbf471a1ec702747aae644ac0504#tmdata/minikube
        datasets:
        - platform.yaml
      config_files:
      - values/values-ral-software.yaml
      datacentre: stfc-ral
  ral-firmware:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?de912ea5e026dbf471a1ec702747aae644ac0504#tmdata/stfc-ral
        datasets:
        - stfc-ral.yaml
        - stations/stfc-ral-firmware.yaml
    - config_files:
      - values/values-ral-firmware.yaml
      datacentre: stfc-ral
  ral-partial:
    values:
    - telmodel:
      - source: gitlab://gitlab.com/ska-telescope/mccs/ska-low-mccs-common?de912ea5e026dbf471a1ec702747aae644ac0504#tmdata/stfc-ral
        datasets:
        - stfc-ral.yaml
        - stations/stfc-ral-partial.yaml
    - config_files:
      - values/values-ral-partial.yaml
      datacentre: stfc-ral


---

environments:
  {{.Environment.Name}}:
{{- with .Environment.Values | get "datacentre" ""}}
    kubeContext: {{.}}
{{- end}}
    values:
      - .deploy/helmfile.d/templates/tmdata.yaml.gotmpl
      {{- toYaml .Environment.Values.config_files | nindent 6}}

---

repositories:
  - name: skao
    url: https://artefact.skao.int/repository/helm-internal
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: jupyterhub
    url: https://jupyterhub.github.io/helm-chart
  - name: ska-low-mccs-daq
    url: https://gitlab.com/api/v4/projects/40346229/packages/helm/dev/
  - name: ska-tango-devices
    url: https://gitlab.com/api/v4/projects/66823602/packages/helm/dev

releases:
  - name: ska-low-mccs-spshw
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: ../charts/ska-low-mccs-spshw
    values:
      - .deploy/helmfile.d/templates/globals.yaml.gotmpl
      - .deploy/helmfile.d/templates/spshw/daqs.yaml.gotmpl
      - .deploy/helmfile.d/templates/spshw/spsstations.yaml.gotmpl
      - .deploy/helmfile.d/templates/spshw/subracks.yaml.gotmpl
      - .deploy/helmfile.d/templates/spshw/tpms.yaml.gotmpl
      - .deploy/helmfile.d/templates/spshw/ska-low-mccs-daq.yaml.gotmpl
      - .deploy/helmfile.d/templates/helm-values.yaml.gotmpl
      - .deploy/helmfile.d/templates/spshw/pdus.yaml.gotmpl

{{- $_tango_host_provided := dig "platform" "cluster" "services" "tango-base" "tango-host" "" .Values}}
{{- $tango_host_provided := dig "overrides" "cluster" "services" "tango-base" "tango-host" $_tango_host_provided .Values}}
{{- if not $tango_host_provided}}
  - name: ska-tango-base
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-base
    version: ~0.4.7
    values:
      - .deploy/helmfile.d/templates/globals.yaml.gotmpl
{{- end}}

{{- $_skuid_provided := dig "platform" "cluster" "services" "skuid" "url" "" .Values}}
{{- $skuid_provided := dig "overrides" "cluster" "services" "skuid" "url" $_skuid_provided .Values}}
{{- if not $skuid_provided}}
  - name: ska-ser-skuid
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-ser-skuid
    version: ~3.3.3
    values:
      - .deploy/helmfile.d/templates/skuid.yaml
{{- end}}

{{- $_jupyterhub_provided := dig "platform" "cluster" "services" "jupyterhub" false .Values}}
{{- $jupyterhub_provided := dig "overrides" "cluster" "services" "jupyterhub" $_jupyterhub_provided .Values}}
{{- if not $jupyterhub_provided}}
  - name: jupyterhub
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: jupyterhub/jupyterhub
    version: 3.1.0
    values:
      - .deploy/helmfile.d/templates/jupyterhub.yaml
{{- end}}

{{- $_taranta_platform_provided := dig "platform" "cluster" "services" "taranta-platform" false .Values}}
{{- $taranta_platform_provided := dig "overrides" "cluster" "services" "taranta-platform" $_taranta_platform_provided .Values}}
{{- if not $taranta_platform_provided}}
  - name: taranta-dashboard
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-taranta-dashboard
    version: 1.4.1  # TODO: pinning for now because 1.4.2 is breaking
    values:
      - ingress:
          enabled: true
          hostname: "*"
  - name: taranta-dashboard-pvc
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-taranta-dashboard-pvc
    version: 1.4.1  # TODO: pinning for now because 1.4.2 is breaking
  - name: taranta-auth
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-taranta-auth
    version: ~0.1.6
    values:
      - ingress:
          enabled: true
          hostname: "*"
{{- end}}

  - name: taranta
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-taranta
    version: ~2.5.1
    values:
      - .deploy/helmfile.d/templates/taranta.yaml

  - name: tangogql
    namespace: {{.Namespace | default "ska-low-mccs"}}
    chart: skao/ska-tango-tangogql
    version: ~1.3.10
    values:
      - .deploy/helmfile.d/templates/globals.yaml.gotmpl
      - ska-tango-base:
          enabled: false
