apiVersion: v2
description: A Helm chart for deploying the MCCS prototype on Kubernetes
name: ska-low-mccs
version: "0.10.1"
appVersion: "0.10.1"
icon: https://www.skatelescope.org/wp-content/uploads/2016/07/09545_NEW_LOGO_2014.png
dependencies:
- name: ska-tango-util
  version: 0.3.9
  repository: https://artefact.skao.int/repository/helm-internal
- name: ska-tango-base
  version: 0.3.10
  repository: https://artefact.skao.int/repository/helm-internal
  condition: ska-tango-base.enabled,global.sub-system.ska-tango-base.enabled
