# Default values for mccs (ska-low-mccs)
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

system: SW-infrastructure
subsystem: mccs
telescope: SKA-low

labels:
  app: ska-low-mccs
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Main values to control for using the ska-low-mccs subchart

dsconfig:
  # the configuration.json contains the deviceserver (instances)
  # if addition instances are required the need to be defined there
  configuration_file: data/configuration.json
  image:
      registry: nexus.engageska-portugal.pt/ska-docker
      image: tango-dsconfig
      tag: 1.5.0
      pullPolicy: IfNotPresent

# Default docker image - used by all of MCCS
mccs:
  image:
    registry: nexus.engageska-portugal.pt/ska-docker
    image: ska-low-mccs
    tag:  0.2.1 #VERSION: Used to update tags on release - DO NOT REMOVE COMMENT
    pullPolicy: IfNotPresent


# Default ska-low-mccs device server instances
deviceServers:
  # controller has only one instance
  - name: mccs-controller
    function: controller
    domain: ska-low-mccs
    command: "MccsController"
    instances: ["controller"]
    depends_on:
      - device: sys/database/2
  - name: mccs-subarray
    # subarray instances have to be 0-padded to two digits
    function: subarray
    domain: ska-low-mccs
    command: "MccsSubarray"
    instances: ["subarray_01", "subarray_02"]
    depends_on:
      - device: low-mccs/control/control
  - name: mccs-station
    # station instances have to be 0-padded to three digits
    function: station
    domain: ska-low-mccs
    command: "MccsStation"
    instances: ["station_001", "station_002"]
    depends_on:
      - device: low-mccs/control/control
  - name: mccs-tile
    # tile instances have to be 0-padded to four digits
    function: tile
    domain: ska-low-mccs
    command: "MccsTile"
    instances: ["tile_0001", "tile_0002", "tile_0003", "tile_0004"]
    depends_on:
      - device: low-mccs/control/control
  - name: mccs-antenna
    # antenna instances have to be 0-padded to six digits
    function: antenna
    domain: ska-low-mccs
    command: "MccsAntenna"
    instances: ["antenna_000001", "antenna_000002", "antenna_000003", "antenna_000004"]
    depends_on:
      - device: low-mccs/control/control

cli:
  # use the MCCS unix cli tool
  enabled: true
  component: mccs-cli
  function: mccs-cli-tango-client
  domain: interactive-testing
  intent: enabling
  resources:
    requests:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi
    limits:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 128Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi

nodeSelector: {}

affinity: {}

tolerations: []
