# Default values for mccs (ska-low-mccs)
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

display: ":0"
xauthority: "~/.Xauthority"

enabled: true

system: SW-infrastructure
subsystem: mccs
telescope: SKA-low

labels:
  app: ska-low-mccs
annotations:
  app.gitlab.com/app: CI_PROJECT_PATH_SLUG
  app.gitlab.com/env: CI_ENVIRONMENT_SLUG

global:
  minikube: true
  tango_host: databaseds-tango-base-test:10000

resources:
  limits:
    cpu: 60m
    memory: 150Mi
  requests:
    cpu: 20m
    memory: 50Mi


# Default docker image - used by all of MCCS
mccs:
  enabled: true
  image:
    registry: artefact.skao.int
    image: ska-low-mccs
    tag: 0.9.0 #VERSION: Used to update tags on release - DO NOT REMOVE COMMENT
    pullPolicy: IfNotPresent


# Default ska-low-mccs device server instances
deviceServers:
  # controller has only one instance
  controller:
    instances: ["controller"]
    file: "data/controller.yaml"
  subarrays:
    # subarray instances have to be 0-padded to two digits
    instances: ["subarray_01", "subarray_02"]
    file: "data/subarray.yaml"
  stations:
    # station instances have to be 0-padded to three digits
    instances: ["station_001", "station_002"]
    file: "data/station.yaml"
  subracks:
    # subrack instances have to be 0-padded to two digits
    instances: ["subrack_01"]
    file: "data/subrack.yaml"
  tiles:
    # tile instances have to be 0-padded to four digits
    instances: ["tile_0001", "tile_0002", "tile_0003", "tile_0004"]
    file: "data/tile.yaml"
    resources:
      requests:
        memory: 512Mi
      limits:
        memory: 512Mi
  apius:
    # apiu instances have to be 0-padded to three digits
    instances: ["apiu_001", "apiu_002"]
    file: "data/apiu.yaml"
  antennas:
    # antenna instances have to be 0-padded to six digits
    instances: ["antenna_000001", "antenna_000002", "antenna_000003", "antenna_000004",
                "antenna_000005", "antenna_000006", "antenna_000007", "antenna_000008"]
    file: "data/antenna.yaml"     
  station-beams:
    # beam instances have to be 0-padded to three digits
    instances: ["beam_01", "beam_02", "beam_03", "beam_04"]
    file: "data/station-beam.yaml"
  subarray-beams:
    # subarray beam instances have to be 0-padded to two digits
    instances: ["subarraybeam_01", "subarraybeam_02", "subarraybeam_03", "subarraybeam_04"]
    file: "data/subarray-beam.yaml"

cli:
  # use the MCCS unix cli tool
  enabled: true
  component: mccs-cli
  function: mccs-cli-tango-client
  domain: interactive-testing
  intent: enabling
  resources:
    requests:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 512Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi
    limits:
      cpu: 100m     # 00m = 0.1 CPU
      memory: 512Mi # 128Mi = 0.125 GB mem
      ephemeral-storage: 512Mi

nodeSelector: {}

affinity: {}

tolerations: []
