{{ if .Values.global.minikube }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: tangogql-{{ template "tangogql.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: tangogql-{{ template "tangogql.name" . }}-{{ .Release.Name }}
    chart: {{ template "tangogql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/tangogql-{{ template "tangogql.name" . }}-{{ .Release.Namespace }}-{{ .Release.Name }}/
  claimRef:
    name: tangogql-{{ template "tangogql.name" . }}-{{ .Release.Name }}
    namespace: {{ .Release.Namespace }}
{{ end }}
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tangogql-{{ template "tangogql.name" . }}-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: tangogql-{{ template "tangogql.name" . }}-{{ .Release.Name }}
    chart: {{ template "tangogql.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  resources:
    requests:
      storage: 1Gi
{{ if .Values.global.minikube }}
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
{{ else }}
  storageClassName: nfss1
  accessModes:
  - ReadWriteMany
{{ end }}
